---
output: html_document
---

### Stefano Olgiati, PhD, MS
### Department of Quantitative Methods, via dei Caniana 2, Bergamo (ITA) 24129 ### tel  +39 035 20 52 638; fax +39 035 20 52 549 
### email <stefano.olgiati@unibg.it>

```{r echo=FALSE, results='hide'}
library(data.table)
```

# Tidy Data Set

````{r}
# Raw Data
raw.data.GBD <- read.csv("RawData/GBD.csv")
raw.data.WHO <- read.csv("RawData/WHO.csv")
names(raw.data.GBD)
names(raw.data.WHO)
dim(raw.data.GBD)
dim(raw.data.WHO)

# Data Tables
attach(raw.data.GBD)
attach(raw.data.WHO)

DT.GBD <- data.table(raw.data.GBD)
DT.WHO <- data.table(raw.data.WHO)

tables()
```


# Manipulating data to generate tidy datasets
```{r}
# ISO 13 codes of EU nations for 1990/95 - 2010
# Austria, Belgium, Bulgaria, Croatia, Republic of Cyprus, Czech Republic, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden and the UK

ISO13 <- c("AUT",
           "BEL",
           "BGR",
           "HRV",
           "CYP",
           "CZE",
           "DNK",
           "EST",
           "FIN",
           "FRA",
           "DEU",
           "GRC",
           "HUN",
           "IRL",
           "ITA",
           "LVA",
           "LTU",
           "LUX",
           "MLT",
           "NLD",
           "POL",
           "PRT",
           "ROU",
           "SVK",
           "SVN",
           "ESP",
           "SWE",
           "GBR")

data.GBD.1990 <- DT.GBD[DT.GBD$year == "1990" & DT.GBD$age_name == "50-54 years" & DT.GBD$sex_name == "Both" & DT.GBD$iso3 %in% ISO13 , ]
data.GBD.1990.ordered <- data.GBD.1990[order(iso3), ]

data.GBD.2010 <- DT.GBD[DT.GBD$year == "2010" & DT.GBD$age_name == "50-54 years" & DT.GBD$sex_name == "Both" & DT.GBD$iso3 %in% ISO13 , ]
data.GBD.2010.ordered <- data.GBD.2010[order(iso3), ]

data.WHO.1995 <- DT.WHO[DT.WHO$YEAR == "1995" & DT.WHO$GHO == "WHS7_105" & DT.WHO$COUNTRY %in% ISO13,  ]
data.WHO.1995.ordered <- data.WHO.1995[order(COUNTRY), ]

data.WHO.2010 <- DT.WHO[DT.WHO$YEAR == "2010" & DT.WHO$GHO == "WHS7_105" & DT.WHO$COUNTRY %in% ISO13,  ]
data.WHO.2010.ordered <- data.WHO.2010[order(COUNTRY), ]

data.1990 <- data.frame(country=data.GBD.1990.ordered$iso3, le=data.GBD.1990.ordered$le, hale=data.GBD.1990.ordered$hale, the=data.WHO.1995.ordered$Display)

data.2010 <- data.frame(country=data.GBD.2010.ordered$iso3, le=data.GBD.2010.ordered$le, le_ui = data.GBD.2010.ordered$le_ui, hale=data.GBD.2010.ordered$hale, hale_ui = data.GBD.2010.ordered$hale_ui, the=data.WHO.2010.ordered$Display)

# Years Lived with Disease in G20 Countries for 1990 - 2010
yld.1990 <- data.1990$le - data.1990$hale
yld.2010 <- data.2010$le - data.2010$hale

# Tidy Dataset
tidy.data <- data.frame(country=data.2010$country, the_1990=data.1990$the, the_2010=data.2010$the, log_the_1990=log(data.1990$the), log_the_2010=log(data.2010$the), le_1990=data.1990$le,  le_2010=data.2010$le, hale_1990 = data.1990$hale, hale_2010 = data.2010$hale, yld_1990=yld.1990, yld_2010=yld.2010)

# Saving Tidy Dataset to .csv file
write.csv(tidy.data, "TidyData.csv")
```
